"""update_agent_resume_relationship

Revision ID: 0f56395924ef
Revises: 9e4d70777a9e
Create Date: 2025-08-10 11:40:20.508852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f56395924ef'
down_revision: Union[str, Sequence[str], None] = '9e4d70777a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('curr_resume_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'agents', 'resumes', ['curr_resume_id'], ['resume_id'])
    op.drop_constraint(op.f('resumes_agent_id_fkey'), 'resumes', type_='foreignkey')
    op.drop_column('resumes', 'agent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('agent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('resumes_agent_id_fkey'), 'resumes', 'agents', ['agent_id'], ['agent_id'])
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'curr_resume_id')
    # ### end Alembic commands ###
