"""add_agent_status_column

Revision ID: 15c457520110
Revises: 0f56395924ef
Create Date: 2025-08-10 14:50:28.391232

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15c457520110"
down_revision: Union[str, Sequence[str], None] = "0f56395924ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    agentstatus_enum = sa.Enum(
        "QUEUED", "IN_PROGRESS", "COMPLETED", "FAILED", name="agentstatus"
    )
    agentstatus_enum.create(op.get_bind())

    # Add the column using the created enum type
    op.add_column(
        "agents",
        sa.Column("status", agentstatus_enum, nullable=False, server_default="QUEUED"),
    )
    op.create_index(op.f("ix_agents_status"), "agents", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agents_status"), table_name="agents")
    op.drop_column("agents", "status")

    # Drop the enum type
    agentstatus_enum = sa.Enum(name="agentstatus")
    agentstatus_enum.drop(op.get_bind())
    # ### end Alembic commands ###
