"""add_task_id_to_agents

Revision ID: 6d18a2712392
Revises: 15c457520110
Create Date: 2025-08-10 14:59:25.908721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6d18a2712392'
down_revision: Union[str, Sequence[str], None] = '15c457520110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_agents_task_id'), 'agents', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_task_id'), table_name='agents')
    op.drop_column('agents', 'task_id')
    # ### end Alembic commands ###
