services:
  # ========== LOCAL REDIS INSTANCE ==========
  # URL: redis://localhost:8100
  redis:
    container_name: redis
    build: ./redis
    ports:
      - '8100:6379'

  # ========== REDIS INSIGHT UI ==========
  # URL: http://localhost:8200
  redis-insight:
    container_name: redis-insight
    build: ./redis-insight
    ports:
      - '8200:5540'
    depends_on:
      - redis
    environment:
      - RI_REDIS_HOST=redis
      - RI_REDIS_PORT=6379
